# Generated by Django 5.1.2 on 2024-11-11 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedietarypreference',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dietary_preference', serialize=False, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipemealtype',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meal_type', serialize=False, to='recipes.recipe'),
        ),
    ]
