# Generated by Django 5.1.2 on 2025-03-15 07:07

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='mealtype',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegan', 'Vegan'), ('glutenfree', 'Gluten free')], max_length=16),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.TextField(default='Set ingredients for this recipe!'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction_steps',
            field=models.TextField(default='Set instructions for this recipe!'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=29),
        ),
        migrations.DeleteModel(
            name='DietaryPreference',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
    ]
