# Generated by Django 5.1.2 on 2025-03-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredient_recipe_remove_instruction_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
    ]
